pub fn invoke_handler() -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // Character commands
        super::character_commands::get_all_characters,
        super::character_commands::get_character,
        super::character_commands::create_character,
        super::character_commands::create_character_with_avatar,
        super::character_commands::update_character,
        super::character_commands::update_character_card_data,
        super::character_commands::merge_character_card_data,
        super::character_commands::delete_character,
        super::character_commands::rename_character,
        super::character_commands::import_character,
        super::character_commands::export_character,
        super::character_commands::export_character_content,
        super::character_commands::update_avatar,
        super::character_commands::get_character_chats_by_id,
        super::character_commands::clear_character_cache,
        // Chat commands
        super::chat_commands::get_all_chats,
        super::chat_commands::get_chat,
        super::chat_commands::get_character_chats,
        super::chat_commands::create_chat,
        super::chat_commands::add_message,
        super::chat_commands::rename_chat,
        super::chat_commands::delete_chat,
        super::chat_commands::search_chats,
        super::chat_commands::list_chat_summaries,
        super::chat_commands::list_recent_chat_summaries,
        super::chat_commands::import_chat,
        super::chat_commands::export_chat,
        super::chat_commands::backup_chat,
        super::chat_commands::list_chat_backups,
        super::chat_commands::get_chat_backup_raw,
        super::chat_commands::delete_chat_backup,
        super::chat_commands::clear_chat_cache,
        super::chat_commands::get_chat_payload_path,
        super::chat_commands::get_chat_payload_tail,
        super::chat_commands::get_chat_payload_before,
        super::chat_commands::get_chat_payload_before_pages,
        super::chat_commands::save_chat_payload_windowed,
        super::chat_commands::patch_chat_payload_windowed,
        super::chat_commands::save_chat_payload_from_file,
        super::chat_commands::import_character_chats,
        // Group chat commands
        super::group_chat_commands::search_group_chats,
        super::group_chat_commands::list_group_chat_summaries,
        super::group_chat_commands::list_recent_group_chat_summaries,
        super::group_chat_commands::get_group_chat_path,
        super::group_chat_commands::get_group_chat_payload_tail,
        super::group_chat_commands::get_group_chat_payload_before,
        super::group_chat_commands::get_group_chat_payload_before_pages,
        super::group_chat_commands::save_group_chat_payload_windowed,
        super::group_chat_commands::patch_group_chat_payload_windowed,
        super::group_chat_commands::save_group_chat_from_file,
        super::group_chat_commands::delete_group_chat,
        super::group_chat_commands::rename_group_chat,
        super::group_chat_commands::import_group_chat_payload,
        // Chat API commands (TauriTavern extension/memory APIs)
        super::chat_api_commands::get_character_chat_summary,
        super::chat_api_commands::get_character_chat_metadata,
        super::chat_api_commands::set_character_chat_metadata_extension,
        super::chat_api_commands::get_character_chat_store_json,
        super::chat_api_commands::set_character_chat_store_json,
        super::chat_api_commands::update_character_chat_store_json,
        super::chat_api_commands::rename_character_chat_store_key,
        super::chat_api_commands::delete_character_chat_store_json,
        super::chat_api_commands::list_character_chat_store_keys,
        super::chat_api_commands::find_last_character_chat_message,
        super::chat_api_commands::search_character_chat_messages,
        // Group chat API commands
        super::group_chat_api_commands::get_group_chat_summary,
        super::group_chat_api_commands::get_group_chat_metadata,
        super::group_chat_api_commands::set_group_chat_metadata_extension,
        super::group_chat_api_commands::get_group_chat_store_json,
        super::group_chat_api_commands::set_group_chat_store_json,
        super::group_chat_api_commands::update_group_chat_store_json,
        super::group_chat_api_commands::rename_group_chat_store_key,
        super::group_chat_api_commands::delete_group_chat_store_json,
        super::group_chat_api_commands::list_group_chat_store_keys,
        super::group_chat_api_commands::find_last_group_chat_message,
        super::group_chat_api_commands::search_group_chat_messages,
        // Extension store commands (global extension persistence)
        super::extension_store_commands::get_extension_store_json,
        super::extension_store_commands::set_extension_store_json,
        super::extension_store_commands::update_extension_store_json,
        super::extension_store_commands::rename_extension_store_key,
        super::extension_store_commands::delete_extension_store_json,
        super::extension_store_commands::list_extension_store_keys,
        super::extension_store_commands::list_extension_store_tables,
        super::extension_store_commands::delete_extension_store_table,
        super::extension_store_commands::get_extension_store_blob,
        super::extension_store_commands::set_extension_store_blob,
        super::extension_store_commands::delete_extension_store_blob,
        super::extension_store_commands::list_extension_store_blob_keys,
        // User commands
        super::user_commands::get_all_users,
        super::user_commands::get_user,
        super::user_commands::get_user_by_username,
        super::user_commands::create_user,
        super::user_commands::update_user,
        super::user_commands::delete_user,
        // Bootstrap commands
        super::bootstrap_commands::get_bootstrap_snapshot,
        // Settings commands
        super::settings_commands::get_tauritavern_settings,
        super::settings_commands::update_tauritavern_settings,
        #[cfg(any(target_os = "macos", windows, target_os = "linux"))]
        super::runtime_paths_commands::get_runtime_paths,
        #[cfg(any(target_os = "macos", windows, target_os = "linux"))]
        super::runtime_paths_commands::set_data_root,
        super::settings_commands::save_user_settings,
        super::settings_commands::get_sillytavern_settings,
        super::settings_commands::create_settings_snapshot,
        super::settings_commands::get_settings_snapshots,
        super::settings_commands::load_settings_snapshot,
        super::settings_commands::restore_settings_snapshot,
        // Dev logging commands
        super::dev_logging_commands::devlog_append_frontend_logs,
        super::dev_logging_commands::devlog_set_backend_log_stream_enabled,
        super::dev_logging_commands::devlog_get_backend_log_tail,
        super::dev_logging_commands::devlog_export_bundle,
        super::dev_logging_commands::devlog_set_llm_api_log_stream_enabled,
        super::dev_logging_commands::devlog_get_llm_api_log_index,
        super::dev_logging_commands::devlog_get_llm_api_log_preview,
        super::dev_logging_commands::devlog_get_llm_api_log_raw,
        // World info commands
        super::world_info_commands::get_world_info,
        super::world_info_commands::get_world_infos_batch,
        super::world_info_commands::save_world_info,
        super::world_info_commands::delete_world_info,
        super::world_info_commands::import_world_info,
        // User directory commands
        super::user_directory_commands::get_user_directory,
        super::user_directory_commands::get_default_user_directory,
        super::user_directory_commands::ensure_user_directories_exist,
        super::user_directory_commands::ensure_default_user_directories_exist,
        // Secret commands
        super::secret_commands::write_secret,
        super::secret_commands::read_secret_state,
        super::secret_commands::view_secrets,
        super::secret_commands::find_secret,
        super::secret_commands::delete_secret,
        super::secret_commands::rotate_secret,
        super::secret_commands::rename_secret,
        // Content commands
        super::content_commands::initialize_default_content,
        super::content_commands::is_default_content_initialized,
        super::content_commands::download_external_import_url,
        // Data archive commands
        super::data_archive_commands::start_import_data_archive,
        super::data_archive_commands::start_export_data_archive,
        super::data_archive_commands::get_data_archive_imports_root,
        super::data_archive_commands::get_data_archive_job_status,
        super::data_archive_commands::cancel_data_archive_job,
        super::data_archive_commands::save_export_data_archive,
        super::data_archive_commands::cleanup_export_data_archive,
        // iOS file bridge commands
        #[cfg(target_os = "ios")]
        super::ios_file_bridge_commands::ios_import_data_archive_from_picker,
        #[cfg(target_os = "ios")]
        super::ios_file_bridge_commands::ios_share_file,
        #[cfg(target_os = "ios")]
        super::ios_file_bridge_commands::ios_share_export_data_archive,
        // Extension commands
        super::extension_commands::get_extensions,
        super::extension_commands::install_extension,
        super::extension_commands::update_extension,
        super::extension_commands::delete_extension,
        super::extension_commands::get_extension_version,
        super::extension_commands::move_extension,
        super::lan_sync_commands::lan_sync_get_status,
        super::lan_sync_commands::lan_sync_start_server,
        super::lan_sync_commands::lan_sync_stop_server,
        super::lan_sync_commands::lan_sync_enable_pairing,
        super::lan_sync_commands::lan_sync_get_pairing_info,
        super::lan_sync_commands::lan_sync_request_pairing,
        super::lan_sync_commands::lan_sync_confirm_pairing,
        super::lan_sync_commands::lan_sync_list_devices,
        super::lan_sync_commands::lan_sync_remove_device,
        super::lan_sync_commands::lan_sync_sync_from_device,
        super::lan_sync_commands::lan_sync_push_to_device,
        super::lan_sync_commands::lan_sync_set_sync_mode,
        super::lan_sync_commands::lan_sync_clear_sync_mode_override,
        // TT-Sync v2 commands
        super::tt_sync_commands::tt_sync_pair,
        super::tt_sync_commands::tt_sync_list_servers,
        super::tt_sync_commands::tt_sync_remove_server,
        super::tt_sync_commands::tt_sync_pull,
        super::tt_sync_commands::tt_sync_push,
        // File commands
        super::file_commands::upload_user_file,
        super::file_commands::read_user_file_asset,
        super::file_commands::delete_user_file,
        super::file_commands::verify_user_files,
        // Image commands
        super::image_commands::upload_user_image,
        super::image_commands::list_user_images,
        super::image_commands::list_user_image_folders,
        super::image_commands::delete_user_image,
        // Avatar commands
        super::avatar_commands::get_avatars,
        super::avatar_commands::delete_avatar,
        super::avatar_commands::upload_avatar,
        super::avatar_commands::read_user_avatar_asset,
        // Group commands
        super::group_commands::get_all_groups,
        super::group_commands::get_group,
        super::group_commands::create_group,
        super::group_commands::update_group,
        super::group_commands::delete_group,
        super::group_commands::get_group_chat_paths,
        super::group_commands::clear_group_cache,
        // Background commands
        super::background_commands::get_all_backgrounds,
        super::background_commands::get_all_background_metadata,
        super::background_commands::delete_background,
        super::background_commands::rename_background,
        super::background_commands::upload_background,
        super::background_commands::upload_background_from_path,
        super::background_commands::read_thumbnail_asset,
        // Theme commands
        super::theme_commands::save_theme,
        super::theme_commands::delete_theme,
        // Preset commands
        super::preset_commands::save_preset,
        super::preset_commands::delete_preset,
        super::preset_commands::restore_preset,
        super::preset_commands::save_openai_preset,
        super::preset_commands::delete_openai_preset,
        super::preset_commands::list_presets,
        super::preset_commands::preset_exists,
        super::preset_commands::get_preset,
        // Quick reply commands
        super::quick_reply_commands::save_quick_reply_set,
        super::quick_reply_commands::delete_quick_reply_set,
        // Agent runtime commands
        super::agent_commands::start_agent_run,
        super::agent_commands::cancel_agent_run,
        super::agent_commands::read_agent_run_events,
        super::agent_commands::read_agent_workspace_file,
        super::agent_commands::prepare_agent_run_commit,
        super::agent_commands::finalize_agent_run_commit,
        // Chat completion commands
        super::chat_completion_commands::get_chat_completions_status,
        super::chat_completion_commands::generate_chat_completion,
        super::chat_completion_commands::start_chat_completion_stream,
        super::chat_completion_commands::cancel_chat_completion_stream,
        super::chat_completion_commands::cancel_chat_completion_generation,
        // Stable diffusion (local chain) commands
        super::stable_diffusion_commands::sd_handle,
        super::stable_diffusion_commands::cancel_sd_request,
        // Translate commands
        super::translate_commands::translate_text,
        // TTS commands
        super::tts_commands::tts_handle,
        // Tokenizer commands
        super::tokenizer_commands::count_openai_tokens,
        super::tokenizer_commands::count_openai_tokens_batch,
        super::tokenizer_commands::encode_openai_tokens,
        super::tokenizer_commands::decode_openai_tokens,
        super::tokenizer_commands::build_openai_logit_bias,
        // Update commands
        super::update_commands::check_for_update,
        // Bridge commands
        super::bridge::emit_event,
        super::bridge::get_version,
        super::bridge::get_client_version,
        super::bridge::is_ready,
        #[cfg(any(dev, debug_assertions))]
        super::bridge::read_dev_web_resource,
        super::bridge::read_frontend_template,
        super::bridge::read_frontend_extension_template,
        super::bridge::get_notification_permission_state,
        super::bridge::request_notification_permission,
        super::bridge::show_system_notification,
    ]
}
